spring.cloud.aws.dynamodb.endpoint: http://localhost.localstack.cloud:4566/
spring.cloud.aws.sqs.endpoint: http://localhost:4566
spring.cloud.aws.sns.endpoint: http://localhost:4566
aws.region.static: us-east-1
aws.credentials.access-key: test
aws.credentials.secret-key: test
aws.dynamodb.endpoint: http://localhost.localstack.cloud:4566/
