spring:
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        accessKey: test
        secretKey: test
      sqs:
        endpoint: http://localhost:4566
      sns:
        endpoint: http://localhost:4566

aws:
  credentials:
    access-key: test
    secret-key: test
  dynamodb:
    endpoint: http://localhost.localstack.cloud:4566/
  region: us-east-1